// Export utilities for LABL IQ analysis results

export const generateRateSheetPDF = async (analysis: any): Promise<Blob> => {
  // Generate a comprehensive rate sheet
  const content = `LABL IQ Rate Sheet
Generated: ${new Date().toLocaleDateString()}
Analysis ID: ${analysis.id || 'N/A'}

SUMMARY
=======
Total Shipments: ${analysis.summary?.total_shipments || analysis.results?.length || 'N/A'}
Total Base Rate: $${(analysis.summary?.total_base_rate || 0).toFixed(2)}
Total Surcharges: $${(analysis.summary?.total_surcharges || 0).toFixed(2)}
Total Final Rate: $${(analysis.summary?.total_final_rate || 0).toFixed(2)}
Total Savings: $${(analysis.summary?.total_savings || 0).toFixed(2)}
Average Savings %: ${(analysis.summary?.avg_savings_percent || 0).toFixed(1)}%

SETTINGS APPLIED
================
Markup: ${analysis.settings?.markupPercentage || analysis.settings?.markupPct || 0}%
Fuel Surcharge: ${analysis.settings?.fuelSurchargePct || 0}%
DAS Surcharge: $${analysis.settings?.dasSurcharge || 0}
EDAS Surcharge: $${analysis.settings?.edasSurcharge || 0}
Remote Surcharge: $${analysis.settings?.remoteSurcharge || 0}
Dim Divisor: ${analysis.settings?.dimDivisor || 139}

TOP 10 SHIPMENTS BY SAVINGS
============================
${(analysis.results || [])
  .sort((a: any, b: any) => (b.savings || 0) - (a.savings || 0))
  .slice(0, 10)
  .map((r: any, i: number) => 
    `${i + 1}. Row ${r.rowIndex}: $${(r.savings || 0).toFixed(2)} (${(r.savings_percent || 0).toFixed(1)}%)`
  ).join('\n')}

This rate sheet was generated by LABL IQ Shipping Intelligence Platform.
For questions, contact your shipping optimization team.`;

  return new Blob([content], { type: 'text/plain' });
};

export const exportToExcel = async (analysis: any): Promise<Blob> => {
  // Generate comprehensive Excel-like CSV with all data
  const headers = [
    'Row', 'Weight (lbs)', 'Zone', 'Origin ZIP', 'Destination ZIP',
    'Base Rate', 'Fuel Surcharge', 'DAS Surcharge', 'EDAS Surcharge', 
    'Remote Surcharge', 'Total Surcharges', 'Final Rate', 
    'Carrier Rate', 'Savings ($)', 'Savings (%)'
  ];

  const rows = (analysis.results || []).map((result: any) => [
    result.rowIndex || '',
    (result.weight_lbs || result.weight || 0).toFixed(2),
    result.zone || '',
    result.orig_zip || result.origin_zip || '',
    result.dest_zip || result.destination_zip || '',
    (result.base_rate || 0).toFixed(2),
    (result.fuel_surcharge || 0).toFixed(2),
    (result.das_surcharge || 0).toFixed(2),
    (result.edas_surcharge || 0).toFixed(2),
    (result.remote_surcharge || 0).toFixed(2),
    (result.total_surcharges || 0).toFixed(2),
    (result.final_rate || 0).toFixed(2),
    (result.carrier_rate || 0).toFixed(2),
    (result.savings || 0).toFixed(2),
    (result.savings_percent || 0).toFixed(1)
  ]);

  const csvContent = [headers, ...rows]
    .map(row => row.map((cell: any) => `"${cell}"`).join(','))
    .join('\n');

  return new Blob([csvContent], { type: 'text/csv' });
};

export const exportToCSV = async (analysis: any): Promise<Blob> => {
  // Generate detailed CSV export
  const headers = [
    'Row', 'Weight (lbs)', 'Zone', 'Origin ZIP', 'Destination ZIP',
    'Base Rate', 'Fuel Surcharge', 'DAS Surcharge', 'EDAS Surcharge', 
    'Remote Surcharge', 'Total Surcharges', 'Final Rate', 
    'Carrier Rate', 'Savings ($)', 'Savings (%)'
  ];

  const rows = (analysis.results || []).map((result: any) => [
    result.rowIndex || '',
    (result.weight_lbs || result.weight || 0).toFixed(2),
    result.zone || '',
    result.orig_zip || result.origin_zip || '',
    result.dest_zip || result.destination_zip || '',
    (result.base_rate || 0).toFixed(2),
    (result.fuel_surcharge || 0).toFixed(2),
    (result.das_surcharge || 0).toFixed(2),
    (result.edas_surcharge || 0).toFixed(2),
    (result.remote_surcharge || 0).toFixed(2),
    (result.total_surcharges || 0).toFixed(2),
    (result.final_rate || 0).toFixed(2),
    (result.carrier_rate || 0).toFixed(2),
    (result.savings || 0).toFixed(2),
    (result.savings_percent || 0).toFixed(1)
  ]);

  const csvContent = [headers, ...rows]
    .map(row => row.map((cell: any) => `"${cell}"`).join(','))
    .join('\n');

  return new Blob([csvContent], { type: 'text/csv' });
};

export const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
